
name: Modified JavaCI
jobs:
  ubuntu_build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java:
        - 8
        - 11
        - 17
        - 19
    steps:
    - name: Setup Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |-
        python -m pip install --upgrade pip
        pip install inotify
    - name: Run inotifywait
      run: |-
        python3 -c "
        import inotify.adapters
        import inotify.constants
        import os
        from datetime import datetime, timezone
        with open('/home/runner/inotifywait-log-ubuntu_build (${{ matrix.java }}).csv', 'w') as log_file:
          i = inotify.adapters.InotifyTree('/home/runner/work/arthas/arthas', inotify.constants.IN_CREATE | inotify.constants.IN_ACCESS)
          for event in i.event_gen(yield_nones=False):
            (_, type_names, path, filename) = event
            now = datetime.now(timezone.utc).strftime('%Y-%m-%dT%H:%M:%S.%f') + 'Z'
            events = ','.join(type_names)
            log_file.write(f'{now};{path};{filename};{events}\n')
            log_file.flush()
            os.fsync(log_file.fileno())
        " &
    - uses: actions/checkout@v3
    - run: touch optcd-3.txt
    - name: Setup java
      uses: actions/setup-java@v3
      with:
        java-version: ${{ matrix.java }}
        distribution: zulu
        cache: maven
    - run: touch optcd-4.txt
    - name: Build with Maven
      run: mvn clean install -P full
    - run: touch optcd-5.txt
    - name: Upload inotifywait logs
      uses: actions/upload-artifact@v4
      with:
        name: inotifywait-ubuntu_build (${{ matrix.java }})
        path: /home/runner/inotifywait-log-ubuntu_build (${{ matrix.java }}).csv
    name: ubuntu_build (${{ matrix.java }})
  windows_build:
    runs-on: windows-2019
    strategy:
      matrix:
        java:
        - 8
        - 11
    steps:
    - name: Setup Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |-
        python -m pip install --upgrade pip
        pip install inotify
    - name: Run inotifywait
      run: |-
        python3 -c "
        import inotify.adapters
        import inotify.constants
        import os
        from datetime import datetime, timezone
        with open('/home/runner/inotifywait-log-windows_build (${{ matrix.java }}).csv', 'w') as log_file:
          i = inotify.adapters.InotifyTree('/home/runner/work/arthas/arthas', inotify.constants.IN_CREATE | inotify.constants.IN_ACCESS)
          for event in i.event_gen(yield_nones=False):
            (_, type_names, path, filename) = event
            now = datetime.now(timezone.utc).strftime('%Y-%m-%dT%H:%M:%S.%f') + 'Z'
            events = ','.join(type_names)
            log_file.write(f'{now};{path};{filename};{events}\n')
            log_file.flush()
            os.fsync(log_file.fileno())
        " &
    - uses: actions/checkout@v3
    - run: touch optcd-3.txt
    - name: Setup java
      uses: actions/setup-java@v3
      with:
        java-version: ${{ matrix.java }}
        distribution: zulu
        cache: maven
    - run: touch optcd-4.txt
    - name: Build with Maven
      run: mvn clean install -P full
    - run: touch optcd-5.txt
    - name: Upload inotifywait logs
      uses: actions/upload-artifact@v4
      with:
        name: inotifywait-windows_build (${{ matrix.java }})
        path: /home/runner/inotifywait-log-windows_build (${{ matrix.java }}).csv
    name: windows_build (${{ matrix.java }})
  macos_build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        java:
        - 8
        - 11
        os:
        - macos-latest
        - macos-14
    steps:
    - name: Setup Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |-
        python -m pip install --upgrade pip
        pip install inotify
    - name: Run inotifywait
      run: |-
        python3 -c "
        import inotify.adapters
        import inotify.constants
        import os
        from datetime import datetime, timezone
        with open('/home/runner/inotifywait-log-macos_build (${{ matrix.java }}, ${{ matrix.os }}).csv', 'w') as log_file:
          i = inotify.adapters.InotifyTree('/home/runner/work/arthas/arthas', inotify.constants.IN_CREATE | inotify.constants.IN_ACCESS)
          for event in i.event_gen(yield_nones=False):
            (_, type_names, path, filename) = event
            now = datetime.now(timezone.utc).strftime('%Y-%m-%dT%H:%M:%S.%f') + 'Z'
            events = ','.join(type_names)
            log_file.write(f'{now};{path};{filename};{events}\n')
            log_file.flush()
            os.fsync(log_file.fileno())
        " &
    - uses: actions/checkout@v3
    - run: touch optcd-3.txt
    - name: Setup java
      uses: actions/setup-java@v3
      with:
        java-version: ${{ matrix.java }}
        distribution: zulu
        cache: maven
    - run: touch optcd-4.txt
    - name: Build with Maven
      run: mvn clean install -P full
    - run: touch optcd-5.txt
    - name: Upload inotifywait logs
      uses: actions/upload-artifact@v4
      with:
        name: inotifywait-macos_build (${{ matrix.java }}, ${{ matrix.os }})
        path: /home/runner/inotifywait-log-macos_build (${{ matrix.java }}, ${{ matrix.os
          }}).csv
    name: macos_build (${{ matrix.java }}, ${{ matrix.os }})
'on':
- push
- workflow_dispatch
